### ISSUE TITLE
Question/bug report.

### ISSUE THREAD

**Issue by K0-RR** [TelepathicGrunt/Blame#44] opened 2021-07-31 15:45 UTC
Just wanted to ask if this is really not a bug in mostructures, sorry for taking your time if this isn't Blame's fault (I saw the https://github.com/TelepathicGrunt/Blame/issues/41 and was thinking maybe this is related).

Issue link here, I added a space before the issue number to not mention it. https://github.com/frqnny/mostructures/issues/ 50

**Comment by TelepathicGrunt** [comment] 2021-07-31 16:18
i'll have to look closer at mostructures. But the issue report I made for myself is something else. The error is still there but just points at the wrong nbt file where it was another file in the structure.

**Comment by TelepathicGrunt** [comment] 2021-07-31 16:20
I think the issue is this
https://github.com/frqnny/mostructures/blob/c6f5375acaec72fae26822a084858e9f98e439d4/src/main/java/io/github/frqnny/mostructures/structure/VolcanicVentStructure.java#L54

Frqnny injected an non-existent nbt file reference here as a placeholder for the volcano and that is what is being detected by blame

**Comment by TelepathicGrunt** [comment] 2021-07-31 17:14
i looked at the nbt pool path issue report thing i made here that you linked and it seems that bug may not actually exist. or maybe it's an edge case issue that i should've left myself reproduction steps lol. I'll close this as I already commented on mostructure's repo on gathering info for that person's crash

**Closed as completed by TelepathicGrunt** 2021-07-31 17:14 UTC
Labels: Investigate
