### ISSUE TITLE
Incompatible Datapack(s)

### ISSUE THREAD

**Issue by Coraline77447** [TelepathicGrunt/Blame#9] opened 2020-11-22 10:29 UTC
Hi. I'm here to report an issue involving datapacks with this mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds and when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors!!!

**Comment by TelepathicGrunt** [comment] 2020-11-22 13:25
The “incompatible, made for an older Minecraft version” just means the maker of the datapack forgot to change a single number for the pack version but the game will still load the datapack just fine. For example, worldgen datapack layout is the same between pack version 5 and 6 so while the game would complain if it is 5, it would still work just fine.

Although you mention it forcing safe mode which means the pack is indeed fundamentally broken and the pack maker should be the one to fix it.

Can you link or provide me the broken datapacks you found? Once I can see how they are broken, I could try and add blame reports for their issues.

**Comment by Coraline77447** [comment] 2020-11-23 15:55
Thanks for the info about what's been happening to the mods that I've been playing with that has this issue and why I've reported this issue is cause apparently you need to change a number within Blame's datapack which I don't understand why that the games datapack system is telling me that Blame's datapack is incompatible when all that this mod does is tells us which mod caused a crash but if Blame can also tell us which mods have incompatible datapacks that'll give us more info to tell mod owners to update their mod's datapack(s) but can you  please explain to me how I can gather information about this error that I'm experiencing with my mods that I'm playing with cause I don't know anything about datapacks at all, even tho I still don't understand crashes and such but I really, really don't understand datapacks since we cant see any problems with them when a crash occurs 

"but can you  please explain to me how I can gather information about this error that I'm experiencing with my mods that I'm playing with cause I don't know anything about datapacks at all, even tho I still don't understand crashes and such but I really, really don't understand datapacks since we cant see any problems with them when a crash occurs" after I've careful read what you've said I can provide the names for 25 mods that have incompatible datapacks so that maybe you could gather information from them by going to their datapacks and only visually see the errors so that you could add the info to Blame's coding so that Blame could detect the errors regarding to datapacks?, if you could do that then the first 3 our of 25 mods that I can provide are called: 

Artifacts
FTB Ultimate
A.V.A

If that's not what you mean then can you please explain to me what I need to do so that I can provide you with the information that you need so that you can add the errors to Blame's coding so that the mod can detect those errors. I'm willing to help enhance your mod but I'm just confused about where to get the information that you need so that you can enhance the mod by adding this error to Blame's coding or wherever the info will be placed in so blame can then tell us which mods have incompatible datapacks.

**Comment by TelepathicGrunt** [comment] 2020-11-23 17:07
Again, even if the game marks the mod's internal datapack as incompatible, it will still work 99% of the time because barely anything changed between park formats. It just a way to let the user know that a pack was made in an older version of mc and that's it. 

For example, my mods called World Blender and Repurposed Structures here use pack format 5 and thus, the game says it is incompatible but it still works perfectly fine. 
![image](https://user-images.githubusercontent.com/40846040/99992202-05225080-2d84-11eb-957d-458d593375c5.png)
 
![image](https://user-images.githubusercontent.com/40846040/99992253-153a3000-2d84-11eb-810a-f60868d5bb0d.png)


So ignore when the game says it is incompatible as it's more of a lie lol. However, this part `the selected datapacks have errors and asks me to either enter safe mode`, that's the mods or datapacks I want to check out. That error about having to start in safe mode means the mod literally broke their internal datapack badly. I'll check out latest Artifacts, FTB Ultimate, and A.V.A. to see if any of them forces the game to start in safe mode. If they do, I can begin to find out why and possibly make Blame state who it is

**Comment by Coraline77447** [comment] 2020-11-23 17:27
I've just now thought that I can potentially still play with all of the mods that I have that have incompatible datapacks and if the world that I'm not able to rejoin and cant enter safe mode is cause whichever mod I had at the time of the  issue that happened which means that whichever mod caused it literally broke minecraft's datapack system entirely which also means the world literally broke as of the datapack side of it to the point that the world literally can't t load up anymore cause of how damaged the world's datapack was which that may explain why I wasn't able to rejoin the world in safe mode but unfortunately idk which one of my mods that I was playing with that has incompatible datapacks that caused the world to literally brake entirely as of on the datapack side of the world... But if the issue still happened but I were to be able to rejoin the world in safe mode then the problem could've been fixed cause the mod that caused the datapack error wouldn't have damaged the world's datapack entirely. Right?

**Comment by TelepathicGrunt** [comment] 2020-11-23 17:38
If the problematic mod is removed, you should be able to enter the world again. Can you provide me the list of mods you are using? Or a download link to your zipped mod folder? That way I can quickly test and try to find the mod that needs to be removed for you

**Comment by TelepathicGrunt** [comment] 2020-11-23 17:43
Wait, you mentioned FTB Ultimate. Isn't that only 1.12.2? What Minecraft version are you playing on?

**Comment by Coraline77447** [comment] 2020-11-23 17:49
Feed The Beast released a mod that's alot like Vain Miner mod for 1.16.4 but the original date as of when it was created was: May 27, 2020 and was last updated 3 days ago. There are 3 different minecraft versions of FTB Ultimate; 1.12.2, 1.15.2, and 1.16.X (1.16 to 1.16.4) but they dont have 1.16 to 1.16.3 being shown in the files section in FTB Ultimate on curseforge. Even tho they've made a modpack that's called Ultimate but they now have a mod with the same name but only allows you to harvest multiple blocks at once if you hold ` / ~ key. Also I'm playing modded minecraft 1.16.4, Forge 1.16.4, Forge version 35.1.0

(Speaking of Vain Miner, I know that what I'm about to say about Vain Miner ain't important to this issue and all but I sure do miss playing modded minecraft with Vain Miner but that mod hasn't seen an update for a long time, like it's been 2 years or so since the owner of Vain Miner has updated the mod to modern minecraft versions.... But at least I have FTB Ultimate as an alternative for Vain Miner and even has white outlines while holding ` / ~ key.)

**Comment by TelepathicGrunt** [comment] 2020-11-23 18:21
This one? https://feed-the-beast.com/modpack/ftb_unstable_1_16

I put that on with AVA and Artifacts and I did not get the safe mode screen. Weird. Although, the pack froze when I tried to re-enter the fresh world I just made so yeah the modpack seems massively unstable lol

**Comment by TelepathicGrunt** [comment] 2020-12-09 22:23
gonna close this now as i cant seem to reproduce the broken datapack screen that prevent loading into worlds. lmk if you are able to isolate which mod is causing that safe mode thing and then i can act on that mod

**Closed as completed by TelepathicGrunt** 2020-12-09 22:23 UTC
Labels: enhancement
